server:
  port: 8082
  address: 192.168.1.12
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://node1:8081/eureka/,http://node3:8083/eureka/
  instance:
    hostname: node2
    
spring:
  application:
    name: euraka-server
